apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: complex-bandicoot-python-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/complex-bandicoot-python-gitops