apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: complex-bandicoot-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: complex-bandicoot-python 
  name: complex-bandicoot-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: complex-bandicoot-python 
